# Project information
site_name: Grin Documentation
site_url: https://docs.grin.mw
site_author: Grin Developers
site_description: 'Grin Documentation'

# Repository
repo_name: mimblewimble/grin
repo_url: https://github.com/mimblewimble/grin
edit_uri: ../docs/edit/master/docs/

# Copyright
copyright: Copyright &copy; 2016 - 2020 Grin Developers

theme:
  palette:
    scheme: preference
  name: material
  logo: assets/images/grin-logo.svg
  language: en
  features:
    - tabs

# Plugins
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mimblewimble/grin
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/team/grincoin

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.superfences
  - meta


nav:
  - Home: index.md
  - About Grin:
    - Story: about-grin/story.md
    - Privacy: about-grin/privacy.md
    - Scalability: about-grin/scalability.md
    - Transactions: about-grin/transactions.md
    - Proof of Work: about-grin/proof-of-work.md
    - Emission: about-grin/emission.md
    - Community: about-grin/community.md
  - Getting Started:
    - Quickstart:
      - Install: getting-started/quickstart/install.md
      - Initialize: getting-started/quickstart/initialize.md
      - Receive: getting-started/quickstart/receive.md
      - Send: getting-started/quickstart/send.md
    - Wallet: getting-started/wallet.md
    - Full Node: getting-started/full-node.md
    - Community Projects: getting-started/community-projects.md
  - Technical Details:
    - Table of Contents: technical/table-of-contents.md
    - Introduction:
      - Elliptic Curves: technical/introduction/elliptic-curve-cryptography.md
      - Commitments: technical/introduction/commitments.md
      - Mimblewimble: technical/introduction/mimblewimble.md
    - Grin for Bitcoiners: technical/grin-for-bitcoiners.md
    - Building Blocks:
      - Merkle Mountain Ranges (MMRs): technical/building-blocks/merkle-mountain-ranges.md
      - Merkle Proof: technical/building-blocks/merkle-proof.md
      - Switch Commitments: technical/building-blocks/switch-commitments.md
    - Blockchain and Consensus:
      - Coinbase Maturity Rule: technical/blockchain-and-consensus/coinbase-maturity-rule.md
      - Fast Sync: technical/blockchain-and-consensus/fast-sync.md
      - Cuckoo Cycle: technical/blockchain-and-consensus/cuckoo-cycle.md
      - Pruning Blockchain Data: technical/blockchain-and-consensus/pruning-blockchain-data.md
      - State and Storage: technical/blockchain-and-consensus/state-and-storage.md
    - Miscellaneous:
      - Contracts: technical/miscellaneous/contracts.md
      - Dandelion: technical/miscellaneous/dandelion.md
      - Range Proofs Format: technical/miscellaneous/range-proof-format.md
    - Slatepack Integration Guide: technical/slatepack-integration.md
  - Archives:
      - Archives: archives/archives.md
