# Project information
site_name: Grin Documentation
site_url: https://docs.grin.mw
site_author: Grin Developers
site_description: 'Grin Documentation'

# Repository
repo_name: mimblewimble/grin
repo_url: https://github.com/mimblewimble/grin
edit_uri: ../docs/edit/master/docs/

# Copyright
copyright: Copyright &copy; 2016 - 2020 Grin Developers

theme:
  palette:
    scheme: preference
  name: material
  logo: assets/images/grin-logo.svg
  language: en
  features:
    - tabs

# Plugins
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mimblewimble/grin
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/team/grincoin

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.superfences
  - meta


nav:
  - Home: index.md
  - About Grin:
    - Story: about-grin/story.md
    - Privacy: about-grin/privacy.md
    - Scalability: about-grin/scalability.md
    - Transactions: about-grin/transactions.md
    - Proof of Work: about-grin/proof-of-work.md
    - Emission: about-grin/emission.md
    - Community: about-grin/community.md
  - Getting Started:
    - Quickstart:
      - Install: getting-started/quickstart/install.md
      - Initialize: getting-started/quickstart/initialize.md
      - Receive: getting-started/quickstart/receive.md
      - Send: getting-started/quickstart/send.md
    - Wallet: getting-started/wallet.md
    - Node: getting-started/node.md
    - Community Wallets: getting-started/community-wallets.md
  - Wiki:
    - Table of Contents: technical/table-of-contents.md
    - Introduction:
      - Elliptic Curves: technical/introduction/elliptic-curve-cryptography.md
      - Commitments: technical/introduction/commitments.md
      - Mimblewimble: technical/introduction/mimblewimble.md
      - Grin for Bitcoiners: technical/introduction/grin-for-bitcoiners.md
    - Transactions:
      - Slates: technical/transactions/slates.md
      - Slatepack: technical/transactions/slatepack.md
      - Payment Proofs: technical/transactions/payment-proofs.md
      - Contracts: technical/transactions/contracts.md
    - Blocks:
      - Header: technical/blocks/block-header.md
      - Body: technical/blocks/block-body.md
      - Fees & Weight: technical/blocks/fees-and-weight.md
    - Chain State:
      - Merkle Mountain Ranges: technical/chain-state/merkle-mountain-range.md
      - State & Pruning: technical/chain-state/state-and-pruning.md
      - Chain Sync: technical/chain-state/chain-sync.md
    - Proof of Work:
      - Cuckoo Cycle: technical/proof-of-work/cuckoo-cycle.md
      - Difficulty Adjustment: technical/proof-of-work/daa.md
      - Stratum RPC: technical/proof-of-work/stratum-rpc.md
    - Miscellaneous:
      - Dandelion: technical/miscellaneous/dandelion.md
      - Switch Commitments: technical/miscellaneous/switch-commitments.md
      - Coinbase Maturity Rule: technical/miscellaneous/coinbase-maturity-rule.md
      - NRD Kernels: technical/miscellaneous/nrd-kernels.md
    - Security Process:
      - Grin's Security Process: technical/security-process/grin-security-process.md
      - Security Team: technical/security-process/security-team.md
      - Code Audits: technical/security-process/code-audits.md
    - Slatepack Integration Guide: technical/slatepack-integration.md
    - Archives: technical/archives.md
